/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TqclAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/triquetrum/commands/parser/antlr/internal/InternalTqcl.tokens");
	}
}
