/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TqclStandaloneSetup extends TqclStandaloneSetupGenerated {

	def static void doSetup() {
		new TqclStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
