grammar org.eclipse.triquetrum.commands.Tqcl with org.eclipse.xtext.xbase.Xtype

generate tqcl "http://www.eclipse.org/triquetrum/commands/Tqcl"


TriquetrumScript:
	commands+=Command*;
	
Command:
	Insert|Connect;

Insert:
	"insert" obj=QualifiedName ("as" alias=NamedObj)? ("with" parameters += (Parameter)*)?;

Parameter:
	name = QualifiedName "=" value=STRING;


NamedObj:
	name = QualifiedName;  
 
 
Connect:
	"connect" from=NamedObj "to" to=NamedObj;
	
