grammar org.eclipse.triquetrum.commands.Tqcl with org.eclipse.xtext.xbase.Xtype

generate tqcl "http://www.eclipse.org/triquetrum/commands/Tqcl"


TriquetrumScript:
	commands+=Command*;
	
Command:
	(Insert|Connect)";";

Insert:
	"insert" obj=NamedObj ("as" name=NamedObj)? ("with" parameters += (Parameter) ("," parameters+=Parameter)*)?;

Parameter:
	NamedObj "=" value=STRING;


NamedObj:
	name = (QualifiedName|STRING);  
 
 
Connect:
	"connect" from=NamedObj "to" to=NamedObj;
	
