/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.tqcl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.triquetrum.commands.tqcl.Connect#getFrom <em>From</em>}</li>
 *   <li>{@link org.eclipse.triquetrum.commands.tqcl.Connect#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getConnect()
 * @model
 * @generated
 */
public interface Connect extends Command
{
  /**
   * Returns the value of the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' containment reference.
   * @see #setFrom(NamedObj)
   * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getConnect_From()
   * @model containment="true"
   * @generated
   */
  NamedObj getFrom();

  /**
   * Sets the value of the '{@link org.eclipse.triquetrum.commands.tqcl.Connect#getFrom <em>From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' containment reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(NamedObj value);

  /**
   * Returns the value of the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' containment reference.
   * @see #setTo(NamedObj)
   * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getConnect_To()
   * @model containment="true"
   * @generated
   */
  NamedObj getTo();

  /**
   * Sets the value of the '{@link org.eclipse.triquetrum.commands.tqcl.Connect#getTo <em>To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' containment reference.
   * @see #getTo()
   * @generated
   */
  void setTo(NamedObj value);

} // Connect
