/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.tqcl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.triquetrum.commands.tqcl.Insert#getObj <em>Obj</em>}</li>
 *   <li>{@link org.eclipse.triquetrum.commands.tqcl.Insert#getAlias <em>Alias</em>}</li>
 *   <li>{@link org.eclipse.triquetrum.commands.tqcl.Insert#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getInsert()
 * @model
 * @generated
 */
public interface Insert extends Command
{
  /**
   * Returns the value of the '<em><b>Obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj</em>' attribute.
   * @see #setObj(String)
   * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getInsert_Obj()
   * @model
   * @generated
   */
  String getObj();

  /**
   * Sets the value of the '{@link org.eclipse.triquetrum.commands.tqcl.Insert#getObj <em>Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj</em>' attribute.
   * @see #getObj()
   * @generated
   */
  void setObj(String value);

  /**
   * Returns the value of the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alias</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' containment reference.
   * @see #setAlias(NamedObj)
   * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getInsert_Alias()
   * @model containment="true"
   * @generated
   */
  NamedObj getAlias();

  /**
   * Sets the value of the '{@link org.eclipse.triquetrum.commands.tqcl.Insert#getAlias <em>Alias</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' containment reference.
   * @see #getAlias()
   * @generated
   */
  void setAlias(NamedObj value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.triquetrum.commands.tqcl.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getInsert_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

} // Insert
