/*******************************************************************************
 * Copyright (c)  2016 Totaro Rodolfo
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *  
 * Contributors:
 *    Rodolfo Totaro - initial API and implementation and/or initial documentation
 *******************************************************************************/
/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.tqcl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.triquetrum.commands.tqcl.Insert#getObj <em>Obj</em>}</li>
 *   <li>{@link org.eclipse.triquetrum.commands.tqcl.Insert#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.triquetrum.commands.tqcl.Insert#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getInsert()
 * @model
 * @generated
 */
public interface Insert extends Command
{
  /**
   * Returns the value of the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Obj</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj</em>' containment reference.
   * @see #setObj(NamedObj)
   * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getInsert_Obj()
   * @model containment="true"
   * @generated
   */
  NamedObj getObj();

  /**
   * Sets the value of the '{@link org.eclipse.triquetrum.commands.tqcl.Insert#getObj <em>Obj</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj</em>' containment reference.
   * @see #getObj()
   * @generated
   */
  void setObj(NamedObj value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(NamedObj)
   * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getInsert_Name()
   * @model containment="true"
   * @generated
   */
  NamedObj getName();

  /**
   * Sets the value of the '{@link org.eclipse.triquetrum.commands.tqcl.Insert#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(NamedObj value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.triquetrum.commands.tqcl.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getInsert_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

} // Insert
