/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.tqcl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.triquetrum.commands.tqcl.TqclPackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends EObject
{
} // Parameter
