/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.tqcl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.eclipse.triquetrum.commands.tqcl.TqclFactory
 * @model kind="package"
 * @generated
 */
public interface TqclPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tqcl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.eclipse.org/triquetrum/commands/Tqcl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tqcl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TqclPackage eINSTANCE = org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl.init();

  /**
   * The meta object id for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.TriquetrumScriptImpl <em>Triquetrum Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.triquetrum.commands.tqcl.impl.TriquetrumScriptImpl
   * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getTriquetrumScript()
   * @generated
   */
  int TRIQUETRUM_SCRIPT = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIQUETRUM_SCRIPT__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Triquetrum Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIQUETRUM_SCRIPT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.triquetrum.commands.tqcl.impl.CommandImpl
   * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.InsertImpl <em>Insert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.triquetrum.commands.tqcl.impl.InsertImpl
   * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getInsert()
   * @generated
   */
  int INSERT = 2;

  /**
   * The feature id for the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__OBJ = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__NAME = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__PARAMETERS = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Insert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.triquetrum.commands.tqcl.impl.ParameterImpl
   * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 3;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.NamedObjImpl <em>Named Obj</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.triquetrum.commands.tqcl.impl.NamedObjImpl
   * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getNamedObj()
   * @generated
   */
  int NAMED_OBJ = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMED_OBJ__VALUE = PARAMETER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMED_OBJ__NAME = PARAMETER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Named Obj</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMED_OBJ_FEATURE_COUNT = PARAMETER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.ConnectImpl <em>Connect</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.triquetrum.commands.tqcl.impl.ConnectImpl
   * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getConnect()
   * @generated
   */
  int CONNECT = 5;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT__FROM = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT__TO = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Connect</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.eclipse.triquetrum.commands.tqcl.TriquetrumScript <em>Triquetrum Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Triquetrum Script</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.TriquetrumScript
   * @generated
   */
  EClass getTriquetrumScript();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.triquetrum.commands.tqcl.TriquetrumScript#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.TriquetrumScript#getCommands()
   * @see #getTriquetrumScript()
   * @generated
   */
  EReference getTriquetrumScript_Commands();

  /**
   * Returns the meta object for class '{@link org.eclipse.triquetrum.commands.tqcl.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link org.eclipse.triquetrum.commands.tqcl.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.Insert
   * @generated
   */
  EClass getInsert();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.triquetrum.commands.tqcl.Insert#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obj</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.Insert#getObj()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Obj();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.triquetrum.commands.tqcl.Insert#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.Insert#getName()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.triquetrum.commands.tqcl.Insert#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.Insert#getParameters()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Parameters();

  /**
   * Returns the meta object for class '{@link org.eclipse.triquetrum.commands.tqcl.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for class '{@link org.eclipse.triquetrum.commands.tqcl.NamedObj <em>Named Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Named Obj</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.NamedObj
   * @generated
   */
  EClass getNamedObj();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.triquetrum.commands.tqcl.NamedObj#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.NamedObj#getValue()
   * @see #getNamedObj()
   * @generated
   */
  EAttribute getNamedObj_Value();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.triquetrum.commands.tqcl.NamedObj#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.NamedObj#getName()
   * @see #getNamedObj()
   * @generated
   */
  EAttribute getNamedObj_Name();

  /**
   * Returns the meta object for class '{@link org.eclipse.triquetrum.commands.tqcl.Connect <em>Connect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connect</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.Connect
   * @generated
   */
  EClass getConnect();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.triquetrum.commands.tqcl.Connect#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.Connect#getFrom()
   * @see #getConnect()
   * @generated
   */
  EReference getConnect_From();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.triquetrum.commands.tqcl.Connect#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see org.eclipse.triquetrum.commands.tqcl.Connect#getTo()
   * @see #getConnect()
   * @generated
   */
  EReference getConnect_To();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TqclFactory getTqclFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.TriquetrumScriptImpl <em>Triquetrum Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.triquetrum.commands.tqcl.impl.TriquetrumScriptImpl
     * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getTriquetrumScript()
     * @generated
     */
    EClass TRIQUETRUM_SCRIPT = eINSTANCE.getTriquetrumScript();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIQUETRUM_SCRIPT__COMMANDS = eINSTANCE.getTriquetrumScript_Commands();

    /**
     * The meta object literal for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.triquetrum.commands.tqcl.impl.CommandImpl
     * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.InsertImpl <em>Insert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.triquetrum.commands.tqcl.impl.InsertImpl
     * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getInsert()
     * @generated
     */
    EClass INSERT = eINSTANCE.getInsert();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__OBJ = eINSTANCE.getInsert_Obj();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__NAME = eINSTANCE.getInsert_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__PARAMETERS = eINSTANCE.getInsert_Parameters();

    /**
     * The meta object literal for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.triquetrum.commands.tqcl.impl.ParameterImpl
     * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.NamedObjImpl <em>Named Obj</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.triquetrum.commands.tqcl.impl.NamedObjImpl
     * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getNamedObj()
     * @generated
     */
    EClass NAMED_OBJ = eINSTANCE.getNamedObj();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAMED_OBJ__VALUE = eINSTANCE.getNamedObj_Value();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAMED_OBJ__NAME = eINSTANCE.getNamedObj_Name();

    /**
     * The meta object literal for the '{@link org.eclipse.triquetrum.commands.tqcl.impl.ConnectImpl <em>Connect</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.triquetrum.commands.tqcl.impl.ConnectImpl
     * @see org.eclipse.triquetrum.commands.tqcl.impl.TqclPackageImpl#getConnect()
     * @generated
     */
    EClass CONNECT = eINSTANCE.getConnect();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECT__FROM = eINSTANCE.getConnect_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECT__TO = eINSTANCE.getConnect_To();

  }

} //TqclPackage
