/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.scoping;

import org.eclipse.triquetrum.commands.scoping.AbstractTqclScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TqclScopeProvider extends AbstractTqclScopeProvider {
}
