/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.ui;

import org.eclipse.triquetrum.commands.ui.AbstractTqclUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TqclUiModule extends AbstractTqclUiModule {
  public TqclUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
