/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.validation;

import org.eclipse.triquetrum.commands.validation.AbstractTqclValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TqclValidator extends AbstractTqclValidator {
}
