/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands;

import org.eclipse.triquetrum.commands.TqclStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TqclStandaloneSetup extends TqclStandaloneSetupGenerated {
  public static void doSetup() {
    TqclStandaloneSetup _tqclStandaloneSetup = new TqclStandaloneSetup();
    _tqclStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
