/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands;

import org.eclipse.triquetrum.commands.AbstractTqclRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TqclRuntimeModule extends AbstractTqclRuntimeModule {
}
