/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.scoping;

import org.eclipse.xtext.xbase.scoping.XtypeScopeProvider;

public abstract class AbstractTqclScopeProvider extends XtypeScopeProvider {
}
