/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.ui.tests;

import com.google.inject.Injector;
import org.eclipse.triquetrum.commands.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class TqclUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.eclipse.triquetrum.commands.Tqcl");
	}

}
