/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.tests;

import com.google.inject.Inject;
import org.eclipse.triquetrum.commands.tests.TqclInjectorProvider;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(TqclInjectorProvider.class)
@SuppressWarnings("all")
public class TqclParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field TqclParsingTest.parseHelper refers to the missing type Model");
  }
}
